name: Docker

on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 60
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/whistle:2.9.54
          ghcr.io/${{ github.repository }}:2.9.54
        push: true
